USE [master]
GO

/****** Object:  Database [CryptoDB]    Script Date: 2024-12-25 08:13:15 ******/
CREATE DATABASE [CryptoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CryptoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CryptoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CryptoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CryptoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CryptoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CryptoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CryptoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CryptoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CryptoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CryptoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CryptoDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CryptoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CryptoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CryptoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CryptoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CryptoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CryptoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CryptoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CryptoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CryptoDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CryptoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CryptoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CryptoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CryptoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CryptoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CryptoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CryptoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CryptoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CryptoDB] SET  MULTI_USER 
GO

ALTER DATABASE [CryptoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CryptoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CryptoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CryptoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CryptoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CryptoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CryptoDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [CryptoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CryptoDB] SET  READ_WRITE 
GO

