name: Automate Script Every 24 Hours

on:
  schedule:
    - cron: "0 */24 * * *"  # This schedules the job to run every 12 hours (UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install ODBC Driver 18 for SQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
        sudo apt-get install -y msodbcsql18
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  

    - name: Run the script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SQL_SERVER_USER: ${{ secrets.SQL_SERVER_USER }}
        SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
      run: |
        python App.py
